"""empty message

Revision ID: 27e03c40efcc
Revises: 
Create Date: 2026-06-08 19:58:39.462690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e03c40efcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_category'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ingredient', sa.Text(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('pub_date', sa.DateTime(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('publish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['recipe_category.id'], name=op.f('fk_recipes_category_id_recipe_category')),
    sa.ForeignKeyConstraint(['publish_id'], ['user.id'], name=op.f('fk_recipes_publish_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('user')
    op.drop_table('recipe_category')
    # ### end Alembic commands ###
