"""empty message

Revision ID: 7a96d6836f2f
Revises: 27e03c40efcc
Create Date: 2026-06-09 15:49:14.554684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a96d6836f2f'
down_revision = '27e03c40efcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('varification_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_varification_code')),
    sa.UniqueConstraint('email', name=op.f('uq_varification_code_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('varification_code')
    # ### end Alembic commands ###
