"""empty message

Revision ID: d6a910bc2c8e
Revises: 7a96d6836f2f
Create Date: 2026-06-09 15:52:34.791062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6a910bc2c8e'
down_revision = '7a96d6836f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('varification_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_varification_code_email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('varification_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_varification_code_email'), ['email'], unique=True)

    # ### end Alembic commands ###
